using System;

namespace Modele
{
    public enum Ingredients
    {
        BaseTomate = 0,
        BasePesto = 1,
        BaseCreme = 2,
        Salade = 3,
        Artichaut = 4,
        Mozzarella = 5,
        Ricotta = 6,
        Gorgonzola = 7,
        Coppa = 8,
        Speck = 9,
        Porchetta = 10,
        Saumon = 11,
        Epinard = 12,
        SauceBalsmamique = 13,
        FromageDeChevre = 14,
        Miel = 15,
        Jambon = 16,
        Oeuf = 17,
        Creme = 18,
        Pancetta = 19,
        Tomate = 20,
        Burrata = 21,
        FruitsDeMer = 22,
        SauceCrustacés = 23,
        HuileOlive = 24,
        Mortadelle = 25,
        Pistaches = 26,
        Merguez = 27,
        Mouton = 28,
        SpianataPiccante = 29,
        Poivrons = 30,
        Champignons = 31,
        nduja = 32,
        OignonsRouges = 33,
        Taleggio = 34,
        Scamorza = 35,
        Thon = 36,
        PersilladeCitronée = 37,
        Poulet = 38,
        SauceBarbecue = 39,
        Emmental = 40,
        FourmeAmbert = 41,
        Boeuf = 42,
        Pepperoni = 43,
        FromageARaclette = 44,
        PommesDeTerre = 45,
        Lardons = 46,
        Olives = 47,
        SauceBlancheKebab = 48,
        Ananas = 49,
        Piments = 50,
        SauceSamourai = 51,
        ParmigianoReggiano = 52,
        PateNormale = 53,
        PateMoyenne = 54,
        PateFine = 55
    }
}
